### PR TITLE
[WIP] react: add missing elements H2, H5 and main

### PR DESCRIPTION
**Pull request by myitcv**
Also add a script to help with regeneration of myitcv.io/react

Complement to #117

### CODE REVIEW

**Comment by grkuntzmd** [comment]
I am considering writing a small code generator that will read a `.toml` file containing all of the missing HTML elements and generate the files for `myitcv.io/react`, including the test cases, taking the list of elements from https://developer.mozilla.org/en-US/docs/Web/HTML/Element.

Would this be helpful? Should I place it in `myitcv.io/react/cmd` or create my own public github repository?

**Comment by grkuntzmd** [comment]
I have created the code generator to create (almost) all of the HTML elements that are currently missing. It is located at https://github.com/grkuntzmd/elemental. See [#120](https://github.com/myitcv/react/issues/120) and [#121](https://github.com/myitcv/react/issues/121).

I have run it against the code in `myitcv.io/react` and then ran `go generate ./...`. I cannot complete the tests (`_scripts/run_tests.sh`) because I do not have `chromedriver`.

My PR includes all of the generated elements and test files.

**Comment by myitcv** [comment]
> I am considering writing a small code generator that will read a `.toml` file containing all of the missing HTML elements and generate the files for myitcv.io/react, including the test cases, taking the list of elements from https://developer.mozilla.org/en-US/docs/Web/HTML/Element.

> ...

> I have created the code generator to create (almost) all of the HTML elements that are currently missing. It is located at https://github.com/grkuntzmd/elemental. See #120 and #121.

This is great, thanks!

The ultimate goal is to parse the HTML 5 spec itself (or some canonical form of the spec). But as a first step we can have it use a hand-maintained abstract form of the spec.

> ... read a `.toml` file...

Please can we keep it as Go source? That way we don't gain a dependency... and it's just as easy (if not easier) to maintain/parse etc.

e.g. building on your start

```go
type Element struct {
	Name       string
	Override   string
	Attributes []Attr
}

type Attr struct {
	Name     string
	Override string
	Type     string
}

var elements = []Element{
	{
		Name: "abbr",
	},
	{
		Name: "applet",
		Attributes: []Attr{
			{Name: "align"},
			{Name: "alt"},
		},
	},
}
```


> Would this be helpful? Should I place it in myitcv.io/react/cmd or create my own public github repository?

Yes, please do add it to a PR to have it live in `myitcv.io/react/cmd`

Apologies for the delay in getting to your PRs - will hopefully complete that tomorrow.

**Comment by myitcv** [comment]
@grkuntzmd 

> I cannot complete the tests (_scripts/run_tests.sh) because I do not have chromedriver.

`chromedriver` is available here: https://sites.google.com/a/chromium.org/chromedriver/

Please let me know if you run into any problems because in theory there's nothing that should prevent `_scripts/run_tests.sh` from working.

**Comment by grkuntzmd** [comment]
- All missing HTML5 elements have been generated (including `<s>` => `react.Strike`.
- All tests passing.

I added the code for the element generator to `cmd/elementGen` using an embedded `map` instead of depending on a `.toml` library.

**Comment by grkuntzmd** [comment]
I have updated the fork to include all of the "global" attributes (non-experimental) included in https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes.

For the `tabindex` attribute, since even a zero is significant, I made it a `*int`. If it is non-nil that attributes is added to the HTML. I have made the required modifications to `reactGen`.

All tests are passing, but they don't really test the attributes.

**Comment by myitcv** [comment]
> For the tabindex attribute, since even a zero is significant, I made it a *int.

I'll have a think about this and comment over in #117 

> All tests are passing, but they don't really test the attributes.

Understood; at least testing for the element itself is _something_ 😄 

> I am converting a bootstrap app written in Elm to gopherjs. Bootstrap makes use of all of these weird HTML elements and attributes. That is what is prompting my updates to myitcv.io/react.

Great. Thanks very much for the feedback and contribution.

Once https://github.com/gopherjs/gopherjs/pull/779 lands we can also get support for the `aria-*` attributes (which I believe are well-defined too, unlike the `data-*` attributes)

I'll close this PR now and we can pick things up over in #117

**Pull request closed without merging**
